In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr # mening of o/p is, example for the number is 6186 means at that index is 1 else out of 10000 are 0.

[[1616, 3015, 1377, 965],
 [1616, 3015, 1377, 6894],
 [1616, 7335, 1377, 2054],
 [4472, 7086, 6579, 5026, 5621],
 [4472, 7086, 6579, 5026, 8808],
 [8825, 1616, 655, 1377, 5999],
 [9032, 9188, 8275, 5026]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1616 3015 1377  965]
 [   0    0    0    0 1616 3015 1377 6894]
 [   0    0    0    0 1616 7335 1377 2054]
 [   0    0    0 4472 7086 6579 5026 5621]
 [   0    0    0 4472 7086 6579 5026 8808]
 [   0    0    0 8825 1616  655 1377 5999]
 [   0    0    0    0 9032 9188 8275 5026]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\udemy\python\venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step


array([[[ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [-3.1859804e-02,  4.6271291e-02, -1.0995366e-02,  4.7677908e-02,
          2.4175081e-02, -4.2590808e-02, -2.2357954e-02, -3.9937057e-02,
          1.6433444e-02,  9.2626736e-04],
        [ 1.4361884e-02,  4.7177482e-02,  8.5205324e-03, -4.

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0, 1616, 3015, 1377,  965], dtype=int32)

In [21]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [ 4.9039129e-02, -4.3768693e-02, -1.7859377e-02, -2.5412310e-02,
         -3.5543729e-02,  3.5170738e-02,  1.2691189e-02,  2.8988454e-02,
          3.2663796e-02, -4.8720744e-02],
        [-3.1859804e-02,  4.6271291e-02, -1.0995366e-02,  4.7677908e-02,
          2.4175081e-02, -4.2590808e-02, -2.2357954e-02, -3.9937057e-02,
          1.6433444e-02,  9.2626736e-04],
        [ 1.4361884e-02,  4.7177482e-02,  8.5205324e-03, -4.